name: CI Example

on: [push, pull_request]

jobs:
    test-python:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.12'
         
            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Run tests
              run: pytest -q